### ISSUE TITLE
Crash in machine verifier

### ISSUE THREAD

**Issue by arsenm** [HSAFoundation/HLC-HSAIL-Development-LLVM#14]
This IR crashes the machine verifier:

target datalayout = "e-p:32:32-p1:64:64:64-p2:64:64:64-p3:32:32:32-p4:64:64:64-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n32"
target triple = "hsail64-pc-unknown-amdopencl"

; Function Attrs: nounwind
define spir_kernel void @hsaPy_hsapy_devfn__5F__5F_main_5F__5F__2E_TestScan_2E_test_5F_single_5F_block_2E__3C_locals_3E__2E_scan_5F_block_24_4_2E_array_28_int64_2C__20_1d_2C__20_C_29__2E_array_28_int64_2C__20_1d_2C__20_C_29_(i8 addrspace(1)\* nocapture readnone %_dot_.2, i64 %_dot_.3, i64 %_dot_.4, i64 addrspace(1)\* nocapture %_dot_.5, i64 %_dot_.6, i64 %_dot_.7, i8 addrspace(1)\* nocapture readnone %_dot_.8, i64 %_dot_.9, i64 %_dot_.10, i64 addrspace(1)\* nocapture %_dot_.11, i64 %_dot_.12, i64 %_dot_.13) #0 {
.14:
  ret void
}

; Function Attrs: nounwind
define linkonce_odr spir_func i32 @hsapy_devfn__5F__5F_main_5F__5F__2E_device_5F_scan_5F_generic_24_1_2E_int64_2E_array_28_int64_2C__20_1d_2C__20_C_29_(i64\* nocapture %_dot_.ret, i64 %arg.tid, i8\* %arg.data.0, i64 %arg.data.1, i64 %arg.data.2, i64 addrspace(4)\* %arg.data.3, i64 %arg.data.4.0, i64 %arg.data.5.0) #0 {
entry:
  br i1 undef, label %B40.lr.ph, label %B154

B40.lr.ph:                                        ; preds = %entry
  %_dot_.802 = or i64 undef, 1
  br label %B40

B40:                                              ; preds = %B130, %B40.lr.ph
  br i1 undef, label %B65, label %B130

B65:                                              ; preds = %B40
  %_dot_.134 = add i64 undef, undef
  br label %B130

B130:                                             ; preds = %B65, %B40
  %_dot_.198 = sdiv i64 undef, 2
  br i1 undef, label %B40, label %B154.loopexit

B154.loopexit:                                    ; preds = %B130
  br label %B154

B154:                                             ; preds = %B154.loopexit, %entry
  %_dot_.261 = icmp eq i64 %arg.tid, 0
  br i1 %_dot_.261, label %B206, label %B238.preheader

B206:                                             ; preds = %B154
  br label %B238.preheader

B238.preheader:                                   ; preds = %B206, %B154
  br i1 undef, label %B250.lr.ph, label %B384

B250.lr.ph:                                       ; preds = %B238.preheader
  %_dot_.377 = add i64 undef, 2
  br label %B250

B250:                                             ; preds = %B370, %B250.lr.ph
  br i1 undef, label %B285, label %B370

B285:                                             ; preds = %B250
  br label %B370

B370:                                             ; preds = %B285, %B250
  br i1 undef, label %B250, label %B384.loopexit

B384.loopexit:                                    ; preds = %B370
  br label %B384

B384:                                             ; preds = %B384.loopexit, %B238.preheader
  ret i32 0
}

attributes #0 = { nounwind }
attributes #1 = { "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-realign-stack" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nounwind readnone "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-realign-stack" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

**Comment by arsenm** [comment]
Program received signal SIGSEGV, Segmentation fault.
_int_malloc (av=av@entry=0x7ffff6b38c00 <main_arena>, bytes=bytes@entry=32) at malloc.c:3326
3326    malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff6b38c00 <main_arena>, bytes=bytes@entry=32) at malloc.c:3326
#1  0x00007ffff67f850e in __GI___libc_malloc (bytes=32) at malloc.c:2895
#2  0x0000000000dd3f60 in llvm::BitVector::operator= (this=0x7fffff7ff430, RHS=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/include/llvm/ADT/BitVector.h:438
#3  0x0000000001822428 in (anonymous namespace)::MachineVerifier::visitMachineFunctionBefore (this=0x7fffff7ff388) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:458
#4  0x0000000001821e02 in (anonymous namespace)::MachineVerifier::runOnMachineFunction (this=0x7fffff7ff388, MF=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:298
#5  0x0000000001821b8d in llvm::MachineFunction::verify (this=0x36c93c0, p=0x0, Banner=0x29ac617 "In Register Scavenger")
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:272
#6  0x00000000018a6421 in llvm::RegScavenger::forward (this=0x3683ab0) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/RegisterScavenging.cpp:228
#7  0x00000000007f7f16 in llvm::RegScavenger::forward (this=0x3683ab0, I=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/include/llvm/CodeGen/RegisterScavenging.h:87
#8  0x00000000014d67da in llvm::HSAILInstrInfo::AnalyzeBranch (this=0x367eac0, MBB=..., TBB=@0x7fffff7ffd08: 0x36d0ee8, FBB=@0x7fffff7ffd00: 0x0, Cond=..., AllowModify=false)
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/Target/HSAIL/HSAILInstrInfo.cpp:347
#9  0x0000000001822ccb in (anonymous namespace)::MachineVerifier::visitMachineBasicBlockBefore (this=0x7fffff7fff28, MBB=0x36d0e38)
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:559
#10 0x0000000001821e68 in (anonymous namespace)::MachineVerifier::runOnMachineFunction (this=0x7fffff7fff28, MF=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:301
#11 0x0000000001821b8d in llvm::MachineFunction::verify (this=0x36c93c0, p=0x0, Banner=0x29ac617 "In Register Scavenger")
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:272
#12 0x00000000018a6421 in llvm::RegScavenger::forward (this=0x3683ab0) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/RegisterScavenging.cpp:228
#13 0x00000000007f7f16 in llvm::RegScavenger::forward (this=0x3683ab0, I=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/include/llvm/CodeGen/RegisterScavenging.h:87
#14 0x00000000014d67da in llvm::HSAILInstrInfo::AnalyzeBranch (this=0x367eac0, MBB=..., TBB=@0x7fffff8008a8: 0x36d0ee8, FBB=@0x7fffff8008a0: 0x0, Cond=..., AllowModify=false)
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/Target/HSAIL/HSAILInstrInfo.cpp:347
#15 0x0000000001822ccb in (anonymous namespace)::MachineVerifier::visitMachineBasicBlockBefore (this=0x7fffff800ac8, MBB=0x36d0e38)
    at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:559
#16 0x0000000001821e68 in (anonymous namespace)::MachineVerifier::runOnMachineFunction (this=0x7fffff800ac8, MF=...) at /home/marsenau/src/HLC-HSAIL-Development-LLVM/lib/CodeGen/MachineVerifier.cpp:301
#17 0x0000000001821b8d in llvm::MachineFunction::verify (this=0x36c93c0, p=0x0, Banner=0x29ac617 "In Register Scavenger")
